name: Weather
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests
      - run: |
          curl -o bot.py "https://gist.githubusercontent.com/iiicechoti/821d414359835c4fe9668fa1741a161a/raw/31cd0265f26cb2cabbb212d85fdab2de48e71dca/bot.py"
          cat bot.py
          python bot.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
